### ISSUE TITLE
VECTOR_get_arr retrieving NULL.

### ISSUE THREAD

**Issue by CantBeKarma** [BigETI/pawn-vector#1]
**Input:**
```
TestVectors()
{
    new 
        Vector:vector_test = VECTOR_NULL;

    new string[30];

    VECTOR_resize(vector_test, 3);

    VECTOR_set_str(vector_test, 0, "This is just a test.");
    VECTOR_set_val(vector_test, 1, 305);
    VECTOR_set_val(vector_test, 2, 666);

    VECTOR_get_arr(vector_test, 0, string);
    print(string);
    
    printf("%i", VECTOR_get_val(vector_test, 1));
    printf("%i", VECTOR_get_val(vector_test, 2));

    return 1;
}
```

**Output:**
```
[04:13:53] (null)
[04:13:53] 305
[04:13:53] 666
```

Why is it printing out null for string in this case?

**Comment by BigETI** [comment]
The problem is that it is true that strings are arrays in PAWN, but **arrays are not strings**! `VECTOR_set_str` is a wrapper of `VECTOR_set_arr`, where the array length is the length of the string  + 1 (string terminator). Let's say you want to get an array of a size larger than it actually stored, it will fail. For example your array in a vector has a size of 21, and you expect this function to copy 30 cells, it will simply not do that. To fix this issue just do

```PAWN
VECTOR_get_arr(vector_test, 0, string, min(sizeof string, MEM_get_size(VECTOR_get_ptr(vector_test, 0))));
string[sizeof string - 1] = '\0';
```
assuming that `min` (get minimum value) is defined.

I can understand why this might be confusing. It would be possible to provide string read functions to make this API easier to use.

**Comment by CantBeKarma** [comment]
Oh, I see. Thanks for the informative reply! You should totally provide string read functions, I feel like that would be quite useful and a huge plus overall for sure.

Guess I'll leave this issue open as a reminder, not sure how busy you are afterall.

**Comment by BigETI** [comment]
https://github.com/BigETI/pawn-vector/commit/df3ee8d66f32d252fa5152dd399d8e8390cc1343
